[tool.poetry]
name = "portunlp"
version = "0.0.0"
description = "Python helpers for portuNLP R package"
authors = ["Diogo Ribeiro <diogo.debastos.ribeiro@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
spacy = ">=3.7,<4.0"
numpy = ">=1.26,<2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
mypy = "^1.16.0"

[tool.pytest.ini_options]
testpaths = ["portunlp/tests"]

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.12"

[[tool.mypy.overrides]]
module = "spacy.*"
ignore_missing_imports = true
