"""Portuguese NLP helpers for Python."""

from ._data import ORTHOGRAPHIC_RULES, PORTUGUESE_STOPWORDS, POS_TAG_MAP, SLANG_MAP
from ._spacy import SpacyToken, spacy_analyze, spacy_lemmatize, spacy_pos_tag, spacy_sentencize, spacy_tokenize
from .text import (
    CorpusStatistics,
    KeywordScore,
    ProcessedText,
    analyze_corpus,
    apply_orth_rules,
    apply_orthographic_rules,
    clean_social,
    compute_inverse_document_frequency,
    clean_social_text,
    extract_keywords,
    filter_stopwords,
    generate_ngrams,
    get_stopwords,
    lemmatize_pt,
    load_dict,
    load_dictionary,
    map_pos_tags,
    map_slang,
    normalize_accents,
    normalize_text,
    pos_tag_pt,
    preprocess_text,
    remove_emoji,
    term_frequencies,
    tokenize_pt,
    tokenize_spacy_pt,
    tokenize_text,
)

__all__ = [
    "ORTHOGRAPHIC_RULES",
    "PORTUGUESE_STOPWORDS",
    "POS_TAG_MAP",
    "CorpusStatistics",
    "KeywordScore",
    "ProcessedText",
    "SLANG_MAP",
    "SpacyToken",
    "analyze_corpus",
    "apply_orth_rules",
    "apply_orthographic_rules",
    "clean_social",
    "clean_social_text",
    "compute_inverse_document_frequency",
    "extract_keywords",
    "filter_stopwords",
    "generate_ngrams",
    "get_stopwords",
    "lemmatize_pt",
    "load_dict",
    "load_dictionary",
    "map_pos_tags",
    "map_slang",
    "normalize_accents",
    "normalize_text",
    "pos_tag_pt",
    "preprocess_text",
    "remove_emoji",
    "spacy_analyze",
    "spacy_lemmatize",
    "spacy_pos_tag",
    "spacy_sentencize",
    "spacy_tokenize",
    "term_frequencies",
    "tokenize_pt",
    "tokenize_spacy_pt",
    "tokenize_text",
]
