"""Bundled lexical resources for Portuguese NLP helpers.

Provenance
----------
* ``PORTUGUESE_STOPWORDS`` is curated from the NLTK Portuguese stopword list
  (https://www.nltk.org/, Apache-2.0) and the multilingual ``stopwords-iso``
  project (https://github.com/stopwords-iso, MIT). It covers function words and
  the common conjugations of *ser*, *estar*, *haver*, and *ter*.
* ``SLANG_MAP`` maps frequent Brazilian/Portuguese internet abbreviations to
  their standard forms; entries are hand-curated from common social-media usage.
* ``ORTHOGRAPHIC_RULES`` reflects selected pre-/post-Acordo Ortográfico (AO90)
  spelling normalizations.
* ``PORTUGUESE_CONTRACTIONS`` enumerates preposition + article/determiner
  contractions (de/em/a/por + ...), used by ``expand_contractions``.
"""

from __future__ import annotations

# Pre-/post-Acordo Ortográfico (AO90) and common European->Brazilian spellings.
ORTHOGRAPHIC_RULES: tuple[tuple[str, str], ...] = (
    ("acto", "ato"),
    ("actos", "atos"),
    ("electrico", "elétrico"),
    ("facto", "fato"),
    ("bónus", "bônus"),
    ("acção", "ação"),
    ("acções", "ações"),
    ("óptimo", "ótimo"),
    ("optimo", "ótimo"),
    ("director", "diretor"),
    ("contacto", "contato"),
)

# Frequent internet/social-media abbreviations -> standard Portuguese forms.
SLANG_MAP: dict[str, str] = {
    "vc": "você",
    "vcs": "vocês",
    "tb": "também",
    "tbm": "também",
    "pq": "porque",
    "q": "que",
    "qd": "quando",
    "qdo": "quando",
    "blz": "beleza",
    "vlw": "valeu",
    "flw": "falou",
    "hj": "hoje",
    "agr": "agora",
    "msm": "mesmo",
    "mt": "muito",
    "mto": "muito",
    "cmg": "comigo",
    "ctg": "contigo",
    "sdd": "saudade",
    "sdds": "saudades",
    "dnv": "de novo",
    "gnt": "gente",
    "pfv": "por favor",
    "pf": "por favor",
    "obg": "obrigado",
    "vdd": "verdade",
    "tá": "está",
    "ta": "está",
    "tô": "estou",
    "to": "estou",
    "né": "não é",
    "cadê": "cadê",
}

# Curated from NLTK's Portuguese stopwords and stopwords-iso. "a" is kept first
# so the public ordering is stable.
PORTUGUESE_STOPWORDS: tuple[str, ...] = (
    "a",
    "à",
    "às",
    "ao",
    "aos",
    "aquela",
    "aquelas",
    "aquele",
    "aqueles",
    "aquilo",
    "as",
    "até",
    "com",
    "como",
    "da",
    "das",
    "de",
    "dela",
    "delas",
    "dele",
    "deles",
    "depois",
    "do",
    "dos",
    "e",
    "ela",
    "elas",
    "ele",
    "eles",
    "em",
    "entre",
    "era",
    "eram",
    "éramos",
    "essa",
    "essas",
    "esse",
    "esses",
    "esta",
    "está",
    "estamos",
    "estas",
    "estava",
    "estavam",
    "estávamos",
    "este",
    "esteja",
    "estejam",
    "estejamos",
    "estes",
    "esteve",
    "estive",
    "estivemos",
    "estiver",
    "estivera",
    "estiveram",
    "estivéramos",
    "estiverem",
    "estivermos",
    "estivesse",
    "estivessem",
    "estivéssemos",
    "estou",
    "eu",
    "foi",
    "fomos",
    "for",
    "fora",
    "foram",
    "fôramos",
    "forem",
    "formos",
    "fosse",
    "fossem",
    "fôssemos",
    "fui",
    "há",
    "haja",
    "hajam",
    "hajamos",
    "hão",
    "havemos",
    "hei",
    "houve",
    "houvemos",
    "houver",
    "houvera",
    "houveram",
    "houvéramos",
    "houverão",
    "houverei",
    "houverem",
    "houveremos",
    "houveria",
    "houveriam",
    "houveríamos",
    "houvermos",
    "houvesse",
    "houvessem",
    "houvéssemos",
    "isso",
    "isto",
    "já",
    "lhe",
    "lhes",
    "mais",
    "mas",
    "me",
    "mesmo",
    "meu",
    "meus",
    "minha",
    "minhas",
    "muito",
    "na",
    "não",
    "nas",
    "nem",
    "no",
    "nos",
    "nós",
    "nossa",
    "nossas",
    "nosso",
    "nossos",
    "num",
    "numa",
    "o",
    "os",
    "ou",
    "para",
    "pela",
    "pelas",
    "pelo",
    "pelos",
    "por",
    "qual",
    "quando",
    "que",
    "quem",
    "são",
    "se",
    "seja",
    "sejam",
    "sejamos",
    "sem",
    "ser",
    "será",
    "serão",
    "serei",
    "seremos",
    "seria",
    "seriam",
    "seríamos",
    "seu",
    "seus",
    "só",
    "somos",
    "sou",
    "sua",
    "suas",
    "também",
    "te",
    "tem",
    "tém",
    "temos",
    "tenha",
    "tenham",
    "tenhamos",
    "tenho",
    "terá",
    "terão",
    "terei",
    "teremos",
    "teria",
    "teriam",
    "teríamos",
    "teu",
    "teus",
    "teve",
    "tinha",
    "tinham",
    "tínhamos",
    "tive",
    "tivemos",
    "tiver",
    "tivera",
    "tiveram",
    "tivéramos",
    "tiverem",
    "tivermos",
    "tivesse",
    "tivessem",
    "tivéssemos",
    "tu",
    "tua",
    "tuas",
    "um",
    "uma",
    "você",
    "vocês",
    "vos",
)

# Preposition + article/determiner contractions -> expanded "prep word" form.
PORTUGUESE_CONTRACTIONS: dict[str, str] = {
    # de + ...
    "do": "de o",
    "da": "de a",
    "dos": "de os",
    "das": "de as",
    "dum": "de um",
    "duma": "de uma",
    "duns": "de uns",
    "dumas": "de umas",
    "dele": "de ele",
    "dela": "de ela",
    "deles": "de eles",
    "delas": "de elas",
    "deste": "de este",
    "desta": "de esta",
    "destes": "de estes",
    "destas": "de estas",
    "desse": "de esse",
    "dessa": "de essa",
    "desses": "de esses",
    "dessas": "de essas",
    "daquele": "de aquele",
    "daquela": "de aquela",
    "daqueles": "de aqueles",
    "daquelas": "de aquelas",
    "disto": "de isto",
    "disso": "de isso",
    "daquilo": "de aquilo",
    "daqui": "de aqui",
    "dali": "de ali",
    # em + ...
    "no": "em o",
    "na": "em a",
    "nos": "em os",
    "nas": "em as",
    "num": "em um",
    "numa": "em uma",
    "nuns": "em uns",
    "numas": "em umas",
    "nele": "em ele",
    "nela": "em ela",
    "neles": "em eles",
    "nelas": "em elas",
    "neste": "em este",
    "nesta": "em esta",
    "nestes": "em estes",
    "nestas": "em estas",
    "nesse": "em esse",
    "nessa": "em essa",
    "nesses": "em esses",
    "nessas": "em essas",
    "naquele": "em aquele",
    "naquela": "em aquela",
    "naqueles": "em aqueles",
    "naquelas": "em aquelas",
    "nisto": "em isto",
    "nisso": "em isso",
    "naquilo": "em aquilo",
    # a + ...
    "ao": "a o",
    "aos": "a os",
    "à": "a a",
    "às": "a as",
    "àquele": "a aquele",
    "àquela": "a aquela",
    "àqueles": "a aqueles",
    "àquelas": "a aquelas",
    "àquilo": "a aquilo",
    # por + ...
    "pelo": "por o",
    "pela": "por a",
    "pelos": "por os",
    "pelas": "por as",
}

# Compact hand-curated polarity lexicon in the range [-1.0, 1.0]. Inspired by
# the design of SentiLex-PT and OpLexicon; values are indicative, not corpus
# trained. Common inflected forms are listed explicitly. Lookups fold accents,
# so unaccented spellings (e.g. "otimo") also match.
PORTUGUESE_SENTIMENT_LEXICON: dict[str, float] = {
    # strong positive
    "excelente": 1.0,
    "excelentes": 1.0,
    "ótimo": 1.0,
    "ótima": 1.0,
    "ótimos": 1.0,
    "ótimas": 1.0,
    "maravilhoso": 1.0,
    "maravilhosa": 1.0,
    "incrível": 1.0,
    "incríveis": 1.0,
    "perfeito": 1.0,
    "perfeita": 1.0,
    "fantástico": 1.0,
    "fantástica": 1.0,
    "sensacional": 1.0,
    "espetacular": 1.0,
    "amo": 1.0,
    "adoro": 1.0,
    "adorei": 1.0,
    "amei": 1.0,
    # moderate positive
    "bom": 0.7,
    "boa": 0.7,
    "bons": 0.7,
    "boas": 0.7,
    "feliz": 0.7,
    "felizes": 0.7,
    "alegre": 0.7,
    "alegria": 0.7,
    "amor": 0.7,
    "gostei": 0.7,
    "gosto": 0.6,
    "lindo": 0.7,
    "linda": 0.7,
    "lindos": 0.7,
    "lindas": 0.7,
    "bonito": 0.6,
    "bonita": 0.6,
    "melhor": 0.7,
    "melhores": 0.7,
    "recomendo": 0.7,
    "satisfeito": 0.6,
    "satisfeita": 0.6,
    "contente": 0.6,
    "grato": 0.6,
    "grata": 0.6,
    "gratidão": 0.7,
    "brilhante": 0.7,
    "sucesso": 0.7,
    "vitória": 0.7,
    "qualidade": 0.5,
    "positivo": 0.6,
    "positiva": 0.6,
    # mild positive
    "agradável": 0.5,
    "divertido": 0.5,
    "divertida": 0.5,
    "confortável": 0.5,
    "eficiente": 0.5,
    "rápido": 0.4,
    "esperança": 0.5,
    "paz": 0.5,
    # strong negative
    "péssimo": -1.0,
    "péssima": -1.0,
    "péssimos": -1.0,
    "horrível": -1.0,
    "horríveis": -1.0,
    "terrível": -1.0,
    "terríveis": -1.0,
    "horroroso": -1.0,
    "nojento": -1.0,
    "nojo": -1.0,
    "odeio": -1.0,
    "odiei": -1.0,
    "detesto": -1.0,
    "detestei": -1.0,
    "ódio": -1.0,
    # moderate negative
    "ruim": -0.7,
    "ruins": -0.7,
    "triste": -0.7,
    "tristes": -0.7,
    "tristeza": -0.7,
    "raiva": -0.7,
    "feio": -0.6,
    "feia": -0.6,
    "feios": -0.6,
    "problema": -0.6,
    "problemas": -0.6,
    "defeito": -0.6,
    "defeitos": -0.6,
    "lixo": -0.8,
    "fraco": -0.6,
    "fraca": -0.6,
    "pior": -0.7,
    "piores": -0.7,
    "decepção": -0.7,
    "decepcionado": -0.7,
    "decepcionante": -0.7,
    "insatisfeito": -0.7,
    "frustrado": -0.7,
    "frustrante": -0.7,
    "fracasso": -0.7,
    "derrota": -0.6,
    "negativo": -0.6,
    "negativa": -0.6,
    # mild negative
    "chato": -0.5,
    "chata": -0.5,
    "irritante": -0.6,
    "lento": -0.5,
    "lenta": -0.5,
    "caro": -0.4,
    "difícil": -0.4,
    "sujo": -0.5,
    "medo": -0.5,
    "dor": -0.5,
    "erro": -0.5,
    "erros": -0.5,
    "falha": -0.5,
    "falhas": -0.5,
}

# Words that invert the polarity of the following sentiment words.
SENTIMENT_NEGATIONS: tuple[str, ...] = (
    "não",
    "nunca",
    "jamais",
    "nem",
    "nada",
    "nenhum",
    "nenhuma",
    "ninguém",
)

# Multipliers applied to the polarity of the following sentiment word.
SENTIMENT_INTENSIFIERS: dict[str, float] = {
    "muito": 1.5,
    "bastante": 1.4,
    "extremamente": 1.8,
    "incrivelmente": 1.6,
    "super": 1.5,
    "mega": 1.5,
    "tão": 1.3,
    "demais": 1.5,
    "completamente": 1.6,
    "totalmente": 1.6,
    "realmente": 1.3,
    "absolutamente": 1.6,
    "pouco": 0.5,
    "levemente": 0.5,
    "ligeiramente": 0.5,
}

POS_TAG_MAP: dict[str, str] = {
    "NOUN": "NOUN",
    "VERB": "VERB",
    "ADJ": "ADJ",
    "ADV": "ADV",
    "PRON": "PRON",
    "ADP": "ADP",
    "CCONJ": "CCONJ",
    "SCONJ": "SCONJ",
    "PROPN": "PROPN",
    "DET": "DET",
    "NUM": "NUM",
    "PUNCT": "PUNCT",
    "INTJ": "INTJ",
    "SYM": "SYM",
}
