"""Bundled lexical resources for Portuguese NLP helpers.

Provenance
----------
* ``PORTUGUESE_STOPWORDS`` is curated from the NLTK Portuguese stopword list
  (https://www.nltk.org/, Apache-2.0) and the multilingual ``stopwords-iso``
  project (https://github.com/stopwords-iso, MIT). It covers function words and
  the common conjugations of *ser*, *estar*, *haver*, and *ter*.
* ``SLANG_MAP`` maps frequent Brazilian/Portuguese internet abbreviations to
  their standard forms; entries are hand-curated from common social-media usage.
* ``ORTHOGRAPHIC_RULES`` reflects selected pre-/post-Acordo Ortográfico (AO90)
  spelling normalizations.
* ``PORTUGUESE_CONTRACTIONS`` enumerates preposition + article/determiner
  contractions (de/em/a/por + ...), used by ``expand_contractions``.
"""

from __future__ import annotations

# Pre-/post-Acordo Ortográfico (AO90) and common European->Brazilian spellings.
ORTHOGRAPHIC_RULES: tuple[tuple[str, str], ...] = (
    ("acto", "ato"),
    ("actos", "atos"),
    ("electrico", "elétrico"),
    ("facto", "fato"),
    ("bónus", "bônus"),
    ("acção", "ação"),
    ("acções", "ações"),
    ("óptimo", "ótimo"),
    ("optimo", "ótimo"),
    ("director", "diretor"),
    ("contacto", "contato"),
)

# Frequent internet/social-media abbreviations -> standard Portuguese forms.
SLANG_MAP: dict[str, str] = {
    "vc": "você",
    "vcs": "vocês",
    "tb": "também",
    "tbm": "também",
    "pq": "porque",
    "q": "que",
    "qd": "quando",
    "qdo": "quando",
    "blz": "beleza",
    "vlw": "valeu",
    "flw": "falou",
    "hj": "hoje",
    "agr": "agora",
    "msm": "mesmo",
    "mt": "muito",
    "mto": "muito",
    "cmg": "comigo",
    "ctg": "contigo",
    "sdd": "saudade",
    "sdds": "saudades",
    "dnv": "de novo",
    "gnt": "gente",
    "pfv": "por favor",
    "pf": "por favor",
    "obg": "obrigado",
    "vdd": "verdade",
    "tá": "está",
    "ta": "está",
    "tô": "estou",
    "to": "estou",
    "né": "não é",
    "cadê": "cadê",
}

# Curated from NLTK's Portuguese stopwords and stopwords-iso. "a" is kept first
# so the public ordering is stable.
PORTUGUESE_STOPWORDS: tuple[str, ...] = (
    "a",
    "à",
    "às",
    "ao",
    "aos",
    "aquela",
    "aquelas",
    "aquele",
    "aqueles",
    "aquilo",
    "as",
    "até",
    "com",
    "como",
    "da",
    "das",
    "de",
    "dela",
    "delas",
    "dele",
    "deles",
    "depois",
    "do",
    "dos",
    "e",
    "ela",
    "elas",
    "ele",
    "eles",
    "em",
    "entre",
    "era",
    "eram",
    "éramos",
    "essa",
    "essas",
    "esse",
    "esses",
    "esta",
    "está",
    "estamos",
    "estas",
    "estava",
    "estavam",
    "estávamos",
    "este",
    "esteja",
    "estejam",
    "estejamos",
    "estes",
    "esteve",
    "estive",
    "estivemos",
    "estiver",
    "estivera",
    "estiveram",
    "estivéramos",
    "estiverem",
    "estivermos",
    "estivesse",
    "estivessem",
    "estivéssemos",
    "estou",
    "eu",
    "foi",
    "fomos",
    "for",
    "fora",
    "foram",
    "fôramos",
    "forem",
    "formos",
    "fosse",
    "fossem",
    "fôssemos",
    "fui",
    "há",
    "haja",
    "hajam",
    "hajamos",
    "hão",
    "havemos",
    "hei",
    "houve",
    "houvemos",
    "houver",
    "houvera",
    "houveram",
    "houvéramos",
    "houverão",
    "houverei",
    "houverem",
    "houveremos",
    "houveria",
    "houveriam",
    "houveríamos",
    "houvermos",
    "houvesse",
    "houvessem",
    "houvéssemos",
    "isso",
    "isto",
    "já",
    "lhe",
    "lhes",
    "mais",
    "mas",
    "me",
    "mesmo",
    "meu",
    "meus",
    "minha",
    "minhas",
    "muito",
    "na",
    "não",
    "nas",
    "nem",
    "no",
    "nos",
    "nós",
    "nossa",
    "nossas",
    "nosso",
    "nossos",
    "num",
    "numa",
    "o",
    "os",
    "ou",
    "para",
    "pela",
    "pelas",
    "pelo",
    "pelos",
    "por",
    "qual",
    "quando",
    "que",
    "quem",
    "são",
    "se",
    "seja",
    "sejam",
    "sejamos",
    "sem",
    "ser",
    "será",
    "serão",
    "serei",
    "seremos",
    "seria",
    "seriam",
    "seríamos",
    "seu",
    "seus",
    "só",
    "somos",
    "sou",
    "sua",
    "suas",
    "também",
    "te",
    "tem",
    "tém",
    "temos",
    "tenha",
    "tenham",
    "tenhamos",
    "tenho",
    "terá",
    "terão",
    "terei",
    "teremos",
    "teria",
    "teriam",
    "teríamos",
    "teu",
    "teus",
    "teve",
    "tinha",
    "tinham",
    "tínhamos",
    "tive",
    "tivemos",
    "tiver",
    "tivera",
    "tiveram",
    "tivéramos",
    "tiverem",
    "tivermos",
    "tivesse",
    "tivessem",
    "tivéssemos",
    "tu",
    "tua",
    "tuas",
    "um",
    "uma",
    "você",
    "vocês",
    "vos",
)

# Preposition + article/determiner contractions -> expanded "prep word" form.
PORTUGUESE_CONTRACTIONS: dict[str, str] = {
    # de + ...
    "do": "de o",
    "da": "de a",
    "dos": "de os",
    "das": "de as",
    "dum": "de um",
    "duma": "de uma",
    "duns": "de uns",
    "dumas": "de umas",
    "dele": "de ele",
    "dela": "de ela",
    "deles": "de eles",
    "delas": "de elas",
    "deste": "de este",
    "desta": "de esta",
    "destes": "de estes",
    "destas": "de estas",
    "desse": "de esse",
    "dessa": "de essa",
    "desses": "de esses",
    "dessas": "de essas",
    "daquele": "de aquele",
    "daquela": "de aquela",
    "daqueles": "de aqueles",
    "daquelas": "de aquelas",
    "disto": "de isto",
    "disso": "de isso",
    "daquilo": "de aquilo",
    "daqui": "de aqui",
    "dali": "de ali",
    # em + ...
    "no": "em o",
    "na": "em a",
    "nos": "em os",
    "nas": "em as",
    "num": "em um",
    "numa": "em uma",
    "nuns": "em uns",
    "numas": "em umas",
    "nele": "em ele",
    "nela": "em ela",
    "neles": "em eles",
    "nelas": "em elas",
    "neste": "em este",
    "nesta": "em esta",
    "nestes": "em estes",
    "nestas": "em estas",
    "nesse": "em esse",
    "nessa": "em essa",
    "nesses": "em esses",
    "nessas": "em essas",
    "naquele": "em aquele",
    "naquela": "em aquela",
    "naqueles": "em aqueles",
    "naquelas": "em aquelas",
    "nisto": "em isto",
    "nisso": "em isso",
    "naquilo": "em aquilo",
    # a + ...
    "ao": "a o",
    "aos": "a os",
    "à": "a a",
    "às": "a as",
    "àquele": "a aquele",
    "àquela": "a aquela",
    "àqueles": "a aqueles",
    "àquelas": "a aquelas",
    "àquilo": "a aquilo",
    # por + ...
    "pelo": "por o",
    "pela": "por a",
    "pelos": "por os",
    "pelas": "por as",
}

POS_TAG_MAP: dict[str, str] = {
    "NOUN": "NOUN",
    "VERB": "VERB",
    "ADJ": "ADJ",
    "ADV": "ADV",
    "PRON": "PRON",
    "ADP": "ADP",
    "CCONJ": "CCONJ",
    "SCONJ": "SCONJ",
    "PROPN": "PROPN",
    "DET": "DET",
    "NUM": "NUM",
    "PUNCT": "PUNCT",
    "INTJ": "INTJ",
    "SYM": "SYM",
}
